version: '3' #docker version
services:
  www:
    #image: php:apache
    image: vikram0911/php-app:latest
    volumes:
      - "./:/var/www/html" #synch project dir with container wed dir
    ports:
      - 80:80
      - 443:443 #for future ssl trafic
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root       #this should live in env var 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1   #EQUIVALENT TO TRUE
    volumes:
      - "./db:/docker-entrypoint-initdb.d" #synch persistent sql file wih container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306